### ISSUE TITLE
Background grid not sharp

### ISSUE THREAD

**Issue by HanEmile** [chaosdorf/sonnenstr58#11] opened 2020-07-24 23:23 UTC
The background grid is not sharp at all in the svg:

![2020-07-25-012150_1589x1117_scrot](https://user-images.githubusercontent.com/22756350/88442584-5e4d9800-ce15-11ea-8775-3d8d0e6c6a54.png)

I don't know if this is a problem on my side, can anyone reproduce this?

**Comment by nomaster** [comment] 2020-07-25 09:45
I found a spurious color adjustment on the regarding element and removed it.

Please confirm if the issue is resolved in the attached file (zipped because GitHub doesn't allow SVG attachments)

[sonnenstr58-floor0.zip](https://github.com/chaosdorf/sonnenstr58/files/4975305/sonnenstr58-floor0.zip)

**Comment by HanEmile** [comment] 2020-07-26 12:11
The background grid seems sharp now! :tada: 

![2020-07-26-140956_1265x1080_scrot](https://user-images.githubusercontent.com/22756350/88478556-b5548980-cf49-11ea-8b10-2b5ed250bdfc.png)

This issue is thus resolved, thanks!

**Closed as completed** 2020-07-26 12:11 UTC
Labels: bug
